FROM bellsoft/liberica-openjdk-alpine:17
ARG TOKEN_ARG
ARG MYSQL_HOST_ARG
ARG MYSQL_PORT_ARG
ARG MYSQL_DB_ARG
ARG DB_USER_ARG
ARG DB_PASS_ARG
ARG DB_PASS_ARG
ARG SPRING_DATASOURCE_USERNAME_ARG
ARG SPRING_DATASOURCE_PASSWORD_ARG
ARG SPRING_DATASOURCE_URL_ARG
ENV SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME_ARG
ENV SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD_ARG
ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL_ARG
ENV MYSQL_HOST=$MYSQL_HOST_ARG
ENV MYSQL_PORT=$MYSQL_PORT_ARG
ENV MYSQL_DB=$MYSQL_DB_ARG
ENV DB_USER=$DB_USER_ARG
ENV DB_PASS=$DB_PASS_ARG
ENV TOKEN=$TOKEN_ARG

ARG JAR_FILE=target/*.jar
copy ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app.jar"]